### PR TITLE
Update Primer hook priorities 

### PR DESCRIPTION
**Pull request by EvanHerman**
The new version of primer add's priorities to some functions to allow for more precise injection of content or easier management of the content flow.

This patch add's the required priorities to ensure compatibility with the latest version of primer.

**Requires:** https://github.com/godaddy/wp-primer-theme/pull/146

**Update:** Additional tweaks for WooCommerce styles. For a complete list see https://github.com/godaddy/wp-primer-theme/pull/182

### CODE REVIEW

**Comment by EvanHerman** [comment]
The Escapade theme menu is an outlier among the group of child themes, since it lives on the side. I was unable to find a reasonable method for displaying the woo commerce cart widget. We may want to revisit this at a later date to come up with a solution to integrate it with this theme as well.

**Comment by fjarrett** [comment]
@EvanHerman I'm not really digging the colors inside the Cart flyout menu.

screen shot 2017-02-15 at 2 05 57 pm

**Comment by EvanHerman** [comment]
@fjarrett I agree. Since this theme ewas so unique I had a hard time deciding what colors should map to the wc cart menu. I went with the standard menu item colors.

What do you think about using the menu (sidebar) background color?



<br />

**Comment by fjarrett** [comment]
@EvanHerman I think the contrast will be a little harsh on some schemes. Perhaps we should mimic Primer here and just use a white BG with drop shadow border?

screen shot 2017-02-15 at 9 17 33 pm

**Comment by EvanHerman** [comment]
The latest commit looks like the following:

**Comment by EvanHerman** [comment]
The latest commit fixes the WooCommerce add to cart button overlap/overflow on i10n sites.

I also went ahead and added pagination styles to this branch and closed the other related PR.

**Pull request merged**
